@startuml
left to right direction
actor Visiteur

rectangle "Prototype" {
    Visiteur -- (Ajouter un article)
    Visiteur -- (Voir les articles)
    Visiteur -- (Ajouter des Categories)
    Visiteur -- (Afficher les catégories)
}

@enduml
