@startuml
left to right direction
actor Admin

rectangle "Prototype" {
    Admin -- (Ajouter un article)
    Admin -- (Voir les articles)
    Admin -- (Ajouter des Categories)
    Admin -- (Afficher les catégories)
}

@enduml
